# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
##
version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@7.6.7
jobs:
  codacy-coverage-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-cov
            pip install codecov
      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ~/vrpy/tests/
            pytest --cov
            codecov
      - coverage-reporter/send_report
  
workflows:
  version: 2.1
  build:
    jobs:
      - codacy-coverage-report
