# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.0

orbs:
  codecov: codecov/codecov@1.0.0
  coverage-reporter: codacy/coverage-reporter@7.6.7
jobs:
  "python-3.8":
    docker:
      - image: circleci/python:3.8
    working_directory: ~/vrpy
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-cov
            pip install codecov
      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ~/vrpy/tests/
            pytest --cov
            codecov
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: test-reports
          destination: test-reports

  codacy-coverage-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-cov
            pip install codecov
      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ~/vrpy/tests/
            pytest --cov
            codecov
      - coverage-reporter/send_report
  
workflows:
  version: 2
  build:
    jobs:
      - "python-3.8"
      - codacy-coverage-report
